
title: Speel een deuntje en laat andere acties plaatsvinden terwijl het speelt
hero_image: images/banner.png
description: Speel een deuntje en laat andere acties plaatsvinden terwijl het speelt
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - title: Speel een deuntje en laat andere acties plaatsvinden terwijl het speelt
