title: Play a tune and allow other actions to take place while it is playing
hero_image: images/banner.png
description: Play a tune and allow other actions to take place while it is playing
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - title: Play a tune and allow other actions to take place while it is playing
