
title: Jouer un morceau et permettre à d'autres actions d'avoir lieu pendant qu'il joue
hero_image: images/banner.png
description: Jouer un morceau et permettre à d'autres actions d'avoir lieu pendant qu'il joue
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - title: Jouer un morceau et permettre à d'autres actions d'avoir lieu pendant qu'il joue
